version: "3"
services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile-rest

    env_file: ./.env-app
    ports:
      - 8080:8080
    links:
      - mongodb
  mongodb:
    image: mongo:5.0.6
    env_file: ./.env-db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo/:/docker-entrypoint-initdb.d/
volumes:
  mongo-data:
